on:
  issues:
    types: [opened, edited, milestoned]
        
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name : echo context
          run: echo "${{github.event_name}}"
        - name : echo avi 
          run: echo "Avi is here${{github.event.issue.title}}"